name: Deploy to staging environment

# Controls when the action will run.
on:
  # Triggers the workflow on repository-dispatch event
  repository_dispatch:
    types: [staging-deployment]

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-ecs-workflow:
    # repository name
    name: Graasp Library
    uses: graasp/graasp-deploy/.github/workflows/cdelivery-ecs-library.yml@v1
    # abort previous deployment if a newer one is in progress
    concurrency:
      group: deploy-staging
      cancel-in-progress: true
    # ecs-task-definition template file
    with:
      app-name: $npm_package_name
      app-version: $npm_package_version
      ecs-task-definition: '.aws/graasp-library-stage.json'
      tag: ${{ github.event.client_payload.tag }}
    # required secrets
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
      aws-region: ${{ secrets.AWS_REGION_STAGE }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
      container-name-library: ${{ secrets.CONTAINER_NAME_GRAASP_EXPLORE_STAGE }}
      ecr-repository: ${{ secrets.ECR_REPOSITORY_GRAASP_EXPLORE_STAGE }}
      ecs-cluster: ${{ secrets.ECS_CLUSTER_GRAASP_EXPLORE_STAGE }}
      ecs-service: ${{ secrets.ECS_SERVICE_GRAASP_EXPLORE_STAGE }}
      next-public-api-host: ${{ secrets.NEXT_PUBLIC_API_HOST_STAGE }}
      next-public-domain: ${{ secrets.REACT_APP_DOMAIN_STAGE }}
      next-public-ga-measurement-id: ${{ secrets.REACT_APP_GA_MEASUREMENT_ID_STAGE }}
      next-public-graasp-analytics-host: ${{ secrets.ANALYZER_CLIENT_HOST_STAGE }}
      next-public-graasp-auth-host: ${{ secrets.NEXT_PUBLIC_GRAASP_AUTH_HOST_STAGE }}
      next-public-graasp-builder-host: ${{ secrets.BUILDER_CLIENT_HOST_STAGE }}
      next-public-graasp-perform-host: ${{ secrets.PLAYER_CLIENT_HOST_STAGE }}
      next-public-graasper-id: ${{ secrets.NEXT_PUBLIC_GRAASPER_ID }}
      # to be removed ! we do not use it anymore
      next-public-published-tag-id: ${{ secrets.NEXT_PUBLIC_PUBLISHED_TAG_ID }}
      next-public-sentry-dsn: ${{ secrets.SENTRY_DSN }}
      port: ${{ secrets.PORT }}
