name: Deploy to development environment

# Controls when the action will run.
on:
  # Triggers the workflow on push events only for the main branch
  push:
    branches:
      - main
      - master

  # Allows to run the workflow manually from the Actions tab
  workflow_dispatch:

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-ecs-workflow:
    name: Graasp Library
    # Reference reusable workflow file. Using the commit SHA is the safest for stability and security
    uses: graasp/graasp-deploy/.github/workflows/cintegration-ecs-explorer.yml@7b5dd84304458c3c5ab03cbbde059670f77b1687
    with:
      ecs-task-definition: '.aws/graasp-explorer-dev.json'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      aws-region: ${{ secrets.AWS_REGION_DEV }}
      ecs-cluster: ${{ secrets.ECS_CLUSTER_GRAASP_EXPLORE_DEV }}
      ecs-service: ${{ secrets.ECS_SERVICE_GRAASP_EXPLORE_DEV }}
      ecr-repository: ${{ secrets.ECR_REPOSITORY_GRAASP_EXPLORE_DEV }}
      container-name-explorer: ${{ secrets.CONTAINER_NAME_GRAASP_EXPLORE_DEV }}
      next-public-api-host: ${{ secrets.NEXT_PUBLIC_API_HOST_DEV }}
      next-public-google-analytics-id: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID }}
      next-public-graasp-auth-host: ${{ secrets.NEXT_PUBLIC_GRAASP_AUTH_HOST_DEV }}
      next-public-graasp-builder-host: ${{ secrets.BUILDER_CLIENT_HOST_DEV }}
      next-public-graasp-perform-host: ${{ secrets.PLAYER_CLIENT_HOST_DEV }}
      next-public-graasper-id: ${{ secrets.NEXT_PUBLIC_GRAASPER_ID }}
      next-public-published-tag-id: ${{ secrets.NEXT_PUBLIC_PUBLISHED_TAG_ID }}
      port: ${{ secrets.PORT }}
