name: Cypress CI

# Control when the action will run
on:
  # Triggers the workflow on push events except for the main branch
  push:
    branches-ignore:
      - main
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# Set environment variables that are available to the steps of all jobs in the workflow
# env:
  # Allows to increase Node's max heap size
  # NODE_OPTIONS: '--max_old_space_size=8192'

jobs:

  cypress:
    name: Cypress
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Check-out repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Check out code
        uses: actions/checkout@v3

      - name: Yarn install and Cache dependencies
        uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1
        with:
          cypress: true

      # lint
      - name: Lint and Type checks
        run: yarn next lint

      #  use the Cypress GitHub Action to run Cypress tests within the chrome browser
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: false
          config: baseUrl=http://localhost:3000
          start: yarn start:ci
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 250
          browser: chrome
          quiet: true
          cache-key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        env:
          NEXT_PUBLIC_API_HOST: http://localhost:3000
          NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: G-H48F1X7SWK
          NEXT_PUBLIC_GRAASP_ANALYTICS_HOST: http://localhost:3003
          NEXT_PUBLIC_GRAASP_AUTH_HOST:  http://localhost:3001
          NEXT_PUBLIC_GRAASP_PERFORM_HOST: http://localhost:3112
          NEXT_PUBLIC_GRAASPER_ID: 12345678-dead-beef-cafe-123456789abc
          NEXT_PUBLIC_NODE_ENV: test

      # after the test run completes
      # store any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # - name: coverage report
      #   run: npx nyc report --reporter=text-summary
