name: Cypress CI

# Control when the action will run
on:
  # Triggers the workflow on push events except for the main branch
  push:
    branches-ignore:
      - main
      - master

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-cypress-workflow:
    # Replace with repository name
    name: Cypress caller template
    # Replace 'main' with the hash of a commit, so it points to an specific version of the reusable workflow that is used
    # Reference reusable workflow file. Using the commit SHA is the safest for stability and security
    uses: graasp/graasp-deploy/.github/workflows/cypress.yml@v1
    with:
      # Test values
      NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: G-H48F1X7SWK
      NEXT_PUBLIC_PUBLISHED_TAG_ID: ea9a3b4e-7b67-44c2-a9df-528b6ae5424f
      NEXT_PUBLIC_API_HOST: http://localhost:3000
      NEXT_PUBLIC_GRAASP_AUTH_HOST: http://localhost:3001
      NEXT_PUBLIC_GRAASP_PERFORM_HOST: http://localhost:3112
      GRAASPER_ID: e890a236-3d45-4042-8a95-c91120f4db73
      NEXT_PUBLIC_NODE_ENV: test
    # Insert required secrets based on repository with the following format: ${{ secrets.SECRET_NAME }}
    secrets:
      api-host-test: ${{ secrets.REACT_APP_API_HOST }}
