name: Cypress CI

# Control when the action will run
on:
  # Triggers the workflow on push events except for the main branch
  push:
    branches-ignore:
      - main
      - master

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-cypress-workflow:
    # Replace with repository name
    name: Cypress caller template
    # Replace 'main' with the hash of a commit, so it points to an specific version of the reusable workflow that is used
    # Reference reusable workflow file. Using the commit SHA is the safest for stability and security
    uses: graasp/graasp-deploy/.github/workflows/cypress.yml@v1
    with:
      # Test values
      next-public-google-analytics-id-test: G-H48F1X7SWK
      next-public-published-tag-id-test: ea9a3b4e-7b67-44c2-a9df-528b6ae5424f
      next-public-api-host-test: http://localhost:3000
      next-public-graasp-analytics-host-test: http://localhost:3003
      next-public-graasp-auth-host-test: http://localhost:3001
      next-public-graasp-perform-host-test: http://localhost:3112
      next-public-graasper-id-test: e890a236-3d45-4042-8a95-c91120f4db73
      next-public-node-env-test: test
