name: Deploy to refactor environment

# Controls when the action will run.
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  refactor-deploy-ecs-backend-workflow:
    # repository name
    name: Graasp Library
    uses: graasp/graasp-deploy/.github/workflows/deploy-refactor-library.yml@fix-refactor

    # abort previous deployment if a newer one is in progress
    concurrency:
      group: deploy-refactor
      cancel-in-progress: true

    with:
      # workflow config
      ecs-task-definition: '.aws/refactor.json'
      environment: refactor               

    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
      ecr-repository: ${{ secrets.ECR_REPOSITORY_GRAASP_LIBRARY }}
      ecs-cluster: ${{ secrets.ECS_CLUSTER_GRAASP_LIBRARY }}
      ecs-service: ${{ secrets.ECS_SERVICE_GRAASP_LIBRARY }}
      next-public-ga-measurement-id: ${{ secrets.REACT_APP_GA_MEASUREMENT_ID_STAGE }}
      next-public-sentry-dsn: ${{ secrets.SENTRY_DSN }}
