# Automate releases of new app versions
name: Release new app version

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  # needed for the auto-tag
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@e5c2aa4f6acd6194e00632c8f262cff67ae17873
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
          release-type: node

      - uses: actions/checkout@v4

      - name: Auto Tag
        uses: graasp/graasp-deploy/.github/actions/auto-tag-after-release@v1
        with:
          releases_created: ${{ steps.release.outputs.releases_created }}
          tag_name: ${{ steps.release.outputs.tag_name }}
