name: Sentry Release

on:
  push:
    tags:
      - '*'

jobs:
  sentry-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: yarn install, build
        run: yarn && yarn build

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: graasp-library
        with:
          environment: production
          sourcemaps: './build'
          version: ${{ github.ref }}
